---
# tasks file for nginx_proxy
- name: Configuration file for our proxy site
  template: src=proxysite.j2 dest=/etc/nginx/sites-available/99-proxysites
  with_items: locations

- file: src=/etc/nginx/sites-available/99-proxysites dest=/etc/nginx/sites-enabled/99-proxysites state=link
  notify: restart nginx
